apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
  labels:
    app: reddit-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit-clone
        image: jpaudel8/reddit:16
        ports:
        - containerPort: 3000
        # --- ADD THIS SECTION BELOW ---
        env:
        - name: DATABASE_URL
          value: "mongodb://mongo-service:27017/reddit"
        - name: NEXTAUTH_URL
          value: "http://k8s-default-ingressr-xxxx.elb.amazonaws.com" # <--- REPLACE THIS with your actual ALB URL
        - name: NEXTAUTH_SECRET
          value: "supersecret"